# Generated by Django 3.1.3 on 2020-12-10 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('na', 'N/A')], max_length=20)),
                ('term', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('12', '1 and 2'), ('na', 'N/A')], max_length=20)),
                ('credits', models.IntegerField(default=15)),
                ('department', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('ELE', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_school', models.CharField(choices=[('pre', 'Pre-requisites'), ('co', 'Co-requisites')], default='pre', max_length=3)),
                ('linked_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_module', to='diagram.module')),
                ('parent_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_module', to='diagram.module')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=254)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagram.module')),
            ],
        ),
    ]
