# Generated by Django 3.1.3 on 2021-01-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0003_module_core'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Map',
        ),
        migrations.RemoveField(
            model_name='module',
            name='ELE',
        ),
        migrations.RemoveField(
            model_name='module',
            name='core',
        ),
        migrations.AlterField(
            model_name='module',
            name='category',
            field=models.CharField(blank=True, default='na', max_length=200),
        ),
        migrations.AlterField(
            model_name='module',
            name='department',
            field=models.CharField(choices=[('CSM', 'Camborne School of Mines'), ('Comp', 'Computing'), ('Eng', 'Engineering'), ('Maths', 'Mathematics'), ('NatSci', 'Natural Sciences'), ('Phy', 'Physics and Astronomy'), ('Bio', 'Biosciences'), ('Geo', 'Geography'), ('Other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='module',
            name='sub_category',
            field=models.CharField(blank=True, default='na', max_length=200),
        ),
        migrations.AlterField(
            model_name='module',
            name='term',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('12', '1 and 2'), ('Other', 'Other')], max_length=20),
        ),
    ]
