# Generated by Django 3.1.3 on 2021-02-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0004_auto_20210108_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='website',
        ),
    ]
