# Generated by Django 3.1.3 on 2021-02-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0005_remove_module_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
