# Generated by Django 3.1.3 on 2021-02-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0006_module_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='co_req',
            field=models.CharField(blank=True, default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='module',
            name='pre_req',
            field=models.CharField(blank=True, default='N/A', max_length=200),
        ),
    ]
