# Generated by Django 3.1.3 on 2021-05-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0007_auto_20210226_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='module',
            name='term',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('12', '1 and 2'), ('23', '2 and 3'), ('123', '1, 2 and 3'), ('Other', 'Other')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
    ]
