# Generated by Django 2.2.17 on 2021-01-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='Natural_Sciences_History',
            new_name='core_Physics_BPhys',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='core_Physics',
            new_name='natural_Sciences_History',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='Topic_Pathway',
            new_name='topic_pathway',
        ),
    ]
