# Generated by Django 2.2.17 on 2021-01-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20210115_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='requisites',
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=600),
        ),
        migrations.DeleteModel(
            name='Requisites',
        ),
    ]
