# Generated by Django 2.2.17 on 2021-01-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_auto_20210115_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='name',
            new_name='Name',
        ),
    ]
