# Generated by Django 2.2.17 on 2021-01-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_auto_20210115_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='Name',
            field=models.CharField(max_length=10000),
        ),
    ]
