# Generated by Django 2.2.17 on 2021-01-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_auto_20210115_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='Name',
        ),
        migrations.AddField(
            model_name='module',
            name='core_name',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
