# Generated by Django 2.2.17 on 2021-01-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_auto_20210122_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='department',
            field=models.CharField(max_length=200),
        ),
    ]
