# Generated by Django 2.2.17 on 2021-01-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_auto_20210122_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='Co_req',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='module',
            name='Pre_req',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
    ]
