# Generated by Django 2.2.17 on 2021-01-22 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_auto_20210122_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='core_name',
            new_name='name',
        ),
    ]
